-- MySQL Script generated by MySQL Workbench
-- Tue Dec 20 21:00:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistema_seg_pi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_seg_pi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_seg_pi` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sistema_seg_pi` ;

-- -----------------------------------------------------
-- Table `sistema_seg_pi`.`cat_cpat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_seg_pi`.`cat_cpat` ;

CREATE TABLE IF NOT EXISTS `sistema_seg_pi`.`cat_cpat` (
  `cpat` VARCHAR(100) NOT NULL,
  `ins_centro` VARCHAR(100) NULL DEFAULT NULL,
  `responsable` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cpat`),
  INDEX `responsable` (`responsable` ASC) VISIBLE,
  INDEX `ins_centro` (`ins_centro` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_seg_pi`.`cat_itcentro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_seg_pi`.`cat_itcentro` ;

CREATE TABLE IF NOT EXISTS `sistema_seg_pi`.`cat_itcentro` (
  `it_centro` VARCHAR(100) NOT NULL,
  `nombre_ic` VARCHAR(30) NULL DEFAULT NULL,
  `estado` VARCHAR(30) NULL DEFAULT NULL,
  `cpat` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`it_centro`),
  INDEX `cpat` (`cpat` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_seg_pi`.`cat_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_seg_pi`.`cat_roles` ;

CREATE TABLE IF NOT EXISTS `sistema_seg_pi`.`cat_roles` (
  `t_rol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`t_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_seg_pi`.`cat_tipoproy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_seg_pi`.`cat_tipoproy` ;

CREATE TABLE IF NOT EXISTS `sistema_seg_pi`.`cat_tipoproy` (
  `t_proy` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`t_proy`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_seg_pi`.`cat_tipotramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_seg_pi`.`cat_tipotramite` ;

CREATE TABLE IF NOT EXISTS `sistema_seg_pi`.`cat_tipotramite` (
  `t_tramite` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`t_tramite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_seg_pi`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_seg_pi`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `sistema_seg_pi`.`proyecto` (
  `proyecto` VARCHAR(100) NOT NULL,
  `solicitante` VARCHAR(100) NULL DEFAULT NULL,
  `tipo_proyecto` VARCHAR(10) NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `cpat_asoc` VARCHAR(100) NOT NULL,
  `fecha_captura` DATE NULL DEFAULT NULL,
  `tipo_tramite` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`proyecto`),
  UNIQUE INDEX `proyecto` (`proyecto` ASC) VISIBLE,
  INDEX `fk_solicitante` (`solicitante` ASC) VISIBLE,
  INDEX `fk_tipoProyecto` (`tipo_proyecto` ASC) VISIBLE,
  INDEX `fk_cpatasoc` (`cpat_asoc` ASC) VISIBLE,
  INDEX `fk_tipotramite` (`tipo_tramite` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_seg_pi`.`usuario_sistema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_seg_pi`.`usuario_sistema` ;

CREATE TABLE IF NOT EXISTS `sistema_seg_pi`.`usuario_sistema` (
  `usuario` VARCHAR(100) NOT NULL,
  `password` VARCHAR(300) NULL DEFAULT NULL,
  `inst_centro` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(40) NULL DEFAULT NULL,
  `apellidoP` VARCHAR(40) NULL DEFAULT NULL,
  `apellidoM` VARCHAR(40) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `telefono` VARCHAR(18) NULL DEFAULT NULL,
  `rol` VARCHAR(50) NOT NULL,
  `rfc` VARCHAR(13) NULL DEFAULT NULL,
  `curp` VARCHAR(18) NULL DEFAULT NULL,
  `ine_frente_URL` VARCHAR(300) NULL DEFAULT NULL,
  `ine_reverso_URL` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `usuario` (`usuario` ASC) VISIBLE,
  INDEX `rol` (`rol` ASC) VISIBLE,
  INDEX `inst_centro` (`inst_centro` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
